estimation_node:
  ros__parameters:

    target_spatial_dimension: 3

    target_initial_state:
      [0.0, 0.0, 0.0,
       0.0, 0.0, 0.0]

    target_initial_covariance_diagonal:
      [1.0, 1.0, 1.0,
       1.0, 1.0, 1.0]

    target_acceleration_noise_std: 0.1

    target_position_variance:
      [0.05, 0.05, 0.05]

    target_measurement_topic: "/perception/target_position"
    target_state_topic: "/estimation/target_state"